apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: flask-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      securityContext:
        runAsUser: 1000     # 镜像中必须存在这个用户UID
        fsGroup: 1000       # 数据卷挂在后的目录属组设置为该组
      containers:
      - image: lizhenliang/flask-demo:root
        name: web
        securityContext:
          allowPrivilegeEscalation: false # 不允许提权
