apiVersion: v1
kind: Pod
metadata:
  namespace: istio-system
  name: sercret-pod
spec:
  containers:
  - name: dev-container
    image: nginx:1.18.0
    volumeMounts:
    - name: my-secret
      mountPath: "/etc/secret"
  volumes:
  - name: my-secret
    secret:
      secretName: db2-test
