apiVersion: v1
kind: Pod
metadata:
  name: hello-seccomp
spec:
  #securityContext:
  #  seccompProfile:
  #    type: Localhost
  #    localhostProfile: chmod.json   # Pod所在宿主机目录,默认为/var/lib/kubelet/seccomp
  containers:
  - image: nginx:1.18.0
    name: web
    command: ['sh','-c','sleep 24h']
