apiVersion: v1 
kind: Secret 
metadata:
  name: mysql 
type: Opaque 
data:
  mysql-root-password: "MTIzNDU2" 
---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mysql 
spec:
  selector: 
    matchLabels:
      app: mysql 
  template:
    metadata: 
      labels:
        app: mysql 
    spec:
      containers: 
      - name: db
        image: mysql:5.7.30
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql
              key: mysql-root-password
